// sveltekit/src/routes/(app)/+page.svelte
<script lang="ts">
	export let data;
</script>

<div class="card w-4/12 bg-base-100 shadow-xl">
	<div class="card-body">
		<h2 class="card-title">Welcome {data.profile?.display_name ?? data.session?.user?.email}</h2>
		{#if data.profile?.display_name}
			<p>
				Name: {data.profileInfo?.first_name}
				{data.profileInfo?.last_name}
			</p>
			<p>Display Name: {data.profile?.display_name}</p>
			<p>Dob: {data.profileInfo?.dob}</p>
			<p>Location: {data.profileInfo?.profile_location}</p>
			<h3 class="text-lg font-semibold mt-2">Bio</h3>
			<p>{data.profile?.bio}</p>
			<p class="text-right">
				<a href="{data.website}/u/{data.profile?.slug}" class="btn btn-md btn-outline">View Profile</a
				>
			</p>
		{/if}
	</div>
</div>

// nextjs/app/(app)/page.tsx
import { createClient } from "@/lib/supabase/server";
import { getProfile } from "@/lib/utils";
import get from "just-safe-get";

export const dynamic = "force-dynamic";

export default async function Home() {
  const supabase = await createClient();

  // get profile and session
  const { profile, session } = await getProfile(supabase);

  const profileInfo = get(profile as Profile, "profiles_info") as ProfileInfo;
  const website = "";

  return (
    <div className="card w-4/12 bg-base-100 shadow-xl">
      <div className="card-body">
        <h2 className="card-title">
          Welcome {profile?.display_name ?? session?.user?.email}
        </h2>
        {profile?.display_name ? (
          <>
            <p>
              Name: {profileInfo?.first_name} {profileInfo?.last_name}
            </p>
            <p>Display Name: {profile.display_name}</p>
            <p>Dob: {profileInfo?.dob}</p>
            <p>Location: {profileInfo?.profile_location}</p>
            <h3 className="text-lg font-semibold mt-2">Bio</h3>
            <p>{profile?.bio}</p>
            <p className="text-right">
              <a
                href={`${website}/${profile?.slug}`}
                className="btn btn-md btn-outline"
              >
                View Profile
              </a>
            </p>
          </>
        ) : null}
      </div>
    </div>
  );
}
